name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn && yarn install-client
    - name: Run build
      run: yarn build
      env:
        SKIP_PREFLIGHT_CHECK: true
    - name: Run tests
      run: yarn test --CI=true
      env:
        SKIP_PREFLIGHT_CHECK: true
